elearning/urls.py
from django.contrib import admin
from django.urls import path, re_path

from courses.views import course_list, course_detail, course_add
from students.views import student_detail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', course_list),
    re_path(r'^course_detail/(?P<course_id>\d)$', course_detail, name='course_detail'),
    path('course_add/', course_add, name='course_add'),
    path('student_detail/<int:student_id>', student_detail),
]

courses/models.py
from django.urls import reverse
from django.db import models
from students.models import User


class Course(models.Model):
    name = models.CharField(max_length=250)
    student_ids = models.ManyToManyField(User)

    def get_absolute_url(self):
        return reverse('course_detail', args=(self.id, ))

    def __str__(self):
        return self.name

students/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

courses/forms.py
from django import forms
from .models import Course


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['name', ]

courses/views.py
from django.shortcuts import render, HttpResponseRedirect
from courses.forms import CourseForm
from courses.models import Course


def course_detail(request, course_id):
    course = Course.objects.get(id=course_id)
    return render(request, 'courses/course_detail.html', {'course': course})


def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {
        'courses': courses,
    })


def course_add(request):
    if request.POST:
        form = CourseForm(request.POST)
        if form.is_valid():
            new_course = form.save()
            return HttpResponseRedirect(new_course.get_absolute_url())
    else:
        form = CourseForm()

    return render(request, 'courses/create_course.html', {
        'form': form,
    })

students/views.py
from django.shortcuts import render
from students.models import User


def student_detail(request, student_id):
    student = User.objects.get(id=student_id)

    return render(request, 'students/student_detail.html', {
        'student': student,
    })

courses/templates/courses/course_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test Django Project</title>
</head>
<body>

    <h3>Welcome to {{ course.name }}</h3>

    {% comment %}
    <p> Test </p>
    {% endcomment %}
</body>
</html>

courses/templates/courses/course_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Courses</title>
</head>
<body>

    <h1>Course List</h1>

    <ul>
    {% for course in courses %}
        <li>{{ course.name }}</li>
        <ul>
        {% for student in course.student_ids.all %}
            <li>{{ student }}</li>
        {% endfor %}
        </ul>
    {% endfor %}
    </ul>

</body>
</html>

courses/templates/courses/create_course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Course</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Create A Course</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</body>
</html>

students/templates/students/student_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Students</title>
</head>
<body>

    <h1>Information About: {{ student }}</h1>

    <h3>Courses: </h3>
    <ul>
        {% for course in student.course_set.all %}
            <li>{{ course }}</li>
        {% endfor %}
    </ul>
</body>
</html>